# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainClientWindow")
        MainWindow.resize(801, 615)
        MainWindow.setMinimumSize(QtCore.QSize(756, 534))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_contacts = QtWidgets.QLabel(self.centralwidget)
        self.label_contacts.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.label_contacts.setObjectName("label_contacts")

        self.btn_add_contact = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_contact.setGeometry(QtCore.QRect(30, 520, 121, 28))
        self.btn_add_contact.setObjectName("btn_add_contact")

        self.btn_remove_contact = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove_contact.setGeometry(QtCore.QRect(160, 520, 111, 28))
        self.btn_remove_contact.setObjectName("btn_remove_contact")

        self.label_history = QtWidgets.QLabel(self.centralwidget)
        self.label_history.setGeometry(QtCore.QRect(310, 10, 141, 16))
        self.label_history.setObjectName("label_history")

        self.text_message = QtWidgets.QTextEdit(self.centralwidget)
        self.text_message.setGeometry(QtCore.QRect(310, 380, 471, 121))
        self.text_message.setObjectName("text_message")

        self.label_new_message = QtWidgets.QLabel(self.centralwidget)
        self.label_new_message.setGeometry(QtCore.QRect(310, 360, 400, 16))
        self.label_new_message.setObjectName("label_new_message")

        self.list_contacts = QtWidgets.QListView(self.centralwidget)
        self.list_contacts.setGeometry(QtCore.QRect(10, 30, 281, 471))
        self.list_contacts.setObjectName("list_contacts")

        self.list_messages = QtWidgets.QListView(self.centralwidget)
        self.list_messages.setGeometry(QtCore.QRect(310, 30, 471, 321))
        self.list_messages.setObjectName("list_messages")

        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(610, 520, 161, 28))
        self.btn_send.setObjectName("btn_send")

        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(470, 520, 121, 28))
        self.btn_clear.setObjectName("btn_clear")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menu_exit = QtWidgets.QAction(MainWindow)
        self.menu_exit.setObjectName("menu_exit")
        self.menu_add_contact = QtWidgets.QAction(MainWindow)
        self.menu_add_contact.setObjectName("menu_add_contact")
        self.menu_del_contact = QtWidgets.QAction(MainWindow)
        self.menu_del_contact.setObjectName("menu_del_contact")
        self.menu.addAction(self.menu_exit)
        self.menu_2.addAction(self.menu_add_contact)
        self.menu_2.addAction(self.menu_del_contact)
        self.menu_2.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_clear.clicked.connect(self.text_message.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Чат программа"))
        self.label_contacts.setText(_translate("MainWindow", "Список контактов:"))
        self.btn_add_contact.setText(_translate("MainWindow", "Добавить контакт"))
        self.btn_remove_contact.setText(_translate("MainWindow", "Удалить контакт"))
        self.label_history.setText(_translate("MainWindow", "История сообщений:"))
        self.label_new_message.setText(_translate("MainWindow", "Введите новое сообщение"))
        self.btn_send.setText(_translate("MainWindow", "Отправить сообщение"))
        self.btn_clear.setText(_translate("MainWindow", "Очистить поле"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Контакты"))
        self.menu_exit.setText(_translate("MainWindow", "Выход"))
        self.menu_add_contact.setText(_translate("MainWindow", "Добавить контакт"))
        self.menu_del_contact.setText(_translate("MainWindow", "Удалить контакт"))
